name: Build Production image for FilScraper

on:
  push:
    tags: ["v*"]

env:
  SLACK_CHANNEL: infra-ci-filscraper
  AWS_REGION: us-east-1
  ECR_REPOSITORY: filecoin/filscraper

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cristi-mb/build-be@main
        id: build-be
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          docker-path: ${{ env.DOCKER_PATH }}
          ecr-repository: ${{ env.ECR_REPOSITORY }}
          custom-image-tag: ${{ github.ref_name }}

      - name: Show image tag
        if: steps.build-be.outcome == 'success'
        run: echo "${{ steps.build-be.outputs.image-tag }}"
